name: chimpss
channels:
  - conda-forge
  - salilab
  - defaults
dependencies:
  - python=3.10
  - openmm
  - openmmtools
  - mdtraj
  - mdanalysis
  - pdbfixer
  - openff-toolkit
  - pdb2pqr
  - parmed
  - pymbar
  - mpiplus
  - rdkit
  - scikit-learn
  - numpy
  - scipy
  - jax
  - seaborn
  - netcdf4
  - py3dmol
  - openbabel
  - modeller
  - pip
  - pip:
    - openmmgridforce @ git+https://github.com/jimtufts/openmmgridforce
