#MotorRow
import math
import os
import shutil

import mdtraj as md
import numpy as np
from datetime import datetime
from openmm.app import PDBFile, Simulation, StateDataReporter, DCDReporter
from openmm import (XmlSerializer, LangevinMiddleIntegrator,
                    MonteCarloMembraneBarostat, MonteCarloBarostat)
from openmm.unit import (kelvin, picosecond, femtosecond, bar, nanometer,
                         joule, angstrom, mole)
from typing import List

from MotorRow_utils import get_positions_from_pdb, restrain_atoms, unpack_infiles

class MotorRow():
    """
    Equilibration driver for membrane protein systems.

    Executes a five-step protocol using OpenMM:

        Step 0 — Energy minimization with positional restraints on protein and ligand.
        Step 1 — NVT, 250 ps, restraints on membrane Z and protein XYZ.
        Step 2 — NPT (MonteCarloMembraneBarostat), 250 ps, restraints on membrane Z and protein XYZ.
        Step 3 — NVT, 250 ps, protein restraints only.
        Step 4 — NPT (MonteCarloMembraneBarostat), 2.5 ns, protein restraints only.
        Step 5 — NPT (MonteCarloBarostat), 2.5 ns, no restraints by default.

    Common settings: dt = 2.0 fs, T = 300 K, stdout every 1000 steps, DCD every 500 steps.

    Parameters
    ----------
    pdb_file : str
        Path to the PDB file generated by Bridgeport.
    system_xml : str
        Path to the serialized OpenMM System XML generated by Bridgeport.
    working_directory : str
        Directory to store all simulation output. Created if it does not exist.
    lig_resname : str, optional
        Residue name of the ligand. Default ``'UNK'``.
    lig_chain : str, optional
        Chain ID of the ligand when it is a peptide chain rather than a HETATM
        residue. Default ``None``.
    """
    
    def __init__(self, pdb_file, system_xml, working_directory, lig_resname: str='UNK', lig_chain: str=None):
        """
        Initialize MotorRow from a serialized OpenMM system and PDB topology.

        See class docstring for parameter descriptions.
        """
        #If the working dir is absolute, leave it alone, otherwise make it abs
        if os.path.isabs(working_directory):
            self.abs_work_dir = working_directory
        else:
            self.abs_work_dir = os.path.join(os.getcwd(), working_directory)
        #Ensure that the working dir exists, and if not create it
        if not os.path.isdir(self.abs_work_dir):
            os.makedirs(self.abs_work_dir, exist_ok=True)
        #Get the system xml file (we want to create a system fresh from this every time)
        if system_xml is None or os.path.isabs(system_xml):
            pass
        else:
            shutil.copy(system_xml, os.path.join(self.abs_work_dir, system_xml))
            system_xml = os.path.join(self.abs_work_dir, system_xml)

        self.system_xml = system_xml
        
        #Get the pdbfile, store the topology (and initial positions i guess)
        if os.path.isabs(pdb_file):
            pass
        else:
            shutil.copy(pdb_file, os.path.join(self.abs_work_dir, pdb_file))
            pdb_file = os.path.join(self.abs_work_dir, pdb_file)
        
        pdb = PDBFile(pdb_file)
        self.topology = pdb.topology
        self.lig_resname = lig_resname
        if lig_chain != None:
            lig_chain = lig_chain.strip()
        self.lig_chain = lig_chain

        
    def main(self, pdb_in, restrain_step_5: bool=False, step_5_nsteps: int=1250000):
        """
        Run the standard five-step equilibration protocol.

        Parameters
        ----------
        pdb_in : str
            Path to the input PDB file (initial structure).
        restrain_step_5 : bool, optional
            If True, apply ligand positional restraints during step 5.
            Default False.
        step_5_nsteps : int, optional
            Number of MD steps for step 5. Default 1250000 (2.5 ns at dt=2 fs).

        Returns
        -------
        state_fn : str
            Path to the serialized OpenMM State XML after the final step.
        pdb_fn : str
            Path to the PDB file containing the structure after the final step.
        """
        #IF the pdb is absolute, store other files in that same directory (where the pdb is)
        if os.path.isabs(pdb_in):
            pass
        else:
            shutil.copy(pdb_in, os.path.join(self.abs_work_dir, pdb_in))
            pdb_in = os.path.join(self.abs_work_dir, pdb_in)
        
        #Minimize
        state_fn, pdb_fn = self._minimize(pdb_in)
        #NVT Restrained
        state_fn, pdb_fn = self._run_step(state_fn, 1, nsteps=125000, positions_from_pdb=pdb_fn, restrain_lig=True) #250 ps
        #NPT Restrained
        state_fn, pdb_fn = self._run_step(state_fn, 2, nsteps=125000, positions_from_pdb=pdb_fn, restrain_lig=True) #250 ps
        #NVT no Restraints
        state_fn, pdb_fn = self._run_step(state_fn, 3, nsteps=125000, positions_from_pdb=pdb_fn, restrain_lig=True) #250 ps
        #NPT Membrane Barostat
        state_fn, pdb_fn = self._run_step(state_fn, 4, nsteps=1250000, positions_from_pdb=pdb_fn, restrain_lig=True) #2500 ps
        #NPT Barostat
        state_fn, pdb_fn = self._run_step(state_fn, 5, nsteps=step_5_nsteps, positions_from_pdb=pdb_fn, restrain_lig=restrain_step_5) #2500 ps
        
        return state_fn, pdb_fn
    

    def _describe_state(self, sim: Simulation, name: str = "State"):
        """
        Print the potential energy and maximum force of the simulation.

        Parameters
        ----------
        sim : Simulation
            OpenMM Simulation whose state will be reported.
        name : str, optional
            Label printed alongside the energy. Default ``'State'``.
        """
        state = sim.context.getState(getEnergy=True, getForces=True)
        self.PE = round(state.getPotentialEnergy()._value, 2)
        max_force = round(max(np.sqrt(v.x**2 + v.y**2 + v.z**2) for v in state.getForces()), 2)
        print(f"{name} has energy {self.PE} kJ/mol ", f"with maximum force {max_force} kJ/(mol nm)")
      
        
    def _write_state(self, sim: Simulation, xml_fn: str):
        """
        Serialize the simulation State to an XML file.

        Parameters
        ----------
        sim : Simulation
            OpenMM Simulation whose State will be serialized.
        xml_fn : str
            Output path for the serialized State XML.
        """
        state = sim.context.getState(getPositions=True, getVelocities=True, enforcePeriodicBox=True)
        contents = XmlSerializer.serialize(state)
        with open(xml_fn, 'w') as f:
            f.write(contents)
        print(f'Wrote: {xml_fn}')
 
    
    def _write_system(self, sim: Simulation, xml_fn: str):
        """
        Serialize the simulation System to an XML file.

        Parameters
        ----------
        sim : Simulation
            OpenMM Simulation whose System will be serialized.
        xml_fn : str
            Output path for the serialized System XML.
        """
        with open(xml_fn, 'w') as f:
            f.write(XmlSerializer.serialize(sim.system))
        print(f'Wrote: {xml_fn}')


    def _write_structure(self, sim: Simulation, pdb_fn: str):
        """
        Write the simulation structure to a PDB file and a PBC-wrapped copy.

        Writes two files: the raw PDB and a molecule-imaged ``*_wrapped.pdb``
        with periodic images corrected for visualization.

        Parameters
        ----------
        sim : Simulation
            OpenMM Simulation whose current positions will be written.
        pdb_fn : str
            Output path for the PDB file.
        """
        with open(pdb_fn, 'w') as f:
            PDBFile.writeFile(sim.topology, sim.context.getState(getPositions=True, enforcePeriodicBox=True).getPositions(), f, keepIds=True)
        print(f'Wrote: {pdb_fn}')

        top = md.Topology().from_openmm(sim.topology)
        traj = md.Trajectory(xyz=sim.context.getState(getPositions=True).getPositions(asNumpy=True),
                             topology=top,
                             unitcell_lengths=np.array([sim.context.getState(getPositions=True).getPeriodicBoxVectors(asNumpy=True)[i][i]._value for i in range(3)]),
                             unitcell_angles=np.array([90,90,90]))
        traj.image_molecules(inplace=True)
        wrapped_pdb_fn = os.path.join(os.path.dirname(pdb_fn), os.path.basename(pdb_fn).split('.')[0] + '_wrapped.pdb')
        traj.save_pdb(wrapped_pdb_fn)
        print(f'Wrote: {wrapped_pdb_fn}')

        

    def _minimize(self, pdb_in:str, pdb_out:str=None, state_xml_out:str=None, temp=300.0, dt=2.0, fc_pos: float=40.0):
        """
        Energy-minimize the structure, writing the result to PDB and XML.

        Parameters
        ----------
        pdb_in : str
            Path to the input PDB file to minimize.
        pdb_out : str, optional
            Output path for the minimized PDB. Defaults to
            ``<working_directory>/minimized.pdb``.
        state_xml_out : str, optional
            Output path for the serialized State XML. Defaults to
            ``<working_directory>/minimized.xml``.
        temp : float, optional
            Temperature in Kelvin for the Langevin integrator. Default 300.0.
        dt : float, optional
            Timestep in femtoseconds. Default 2.0.
        fc_pos : float, optional
            Positional restraint force constant (kJ/mol/nm²). Default 40.0.

        Returns
        -------
        state_xml_out : str
            Path to the written State XML file.
        pdb_out : str
            Path to the written minimized PDB file.
        """
        start = datetime.now()
        system, _, positions = unpack_infiles(self.system_xml, pdb_in) 

        # Add restraint to ligand
        crds, prt_heavy_atoms, mem_heavy_atoms, lig_heavy_atoms = get_positions_from_pdb(pdb_in, lig_resname=self.lig_resname, lig_chain=self.lig_chain)
        if len(lig_heavy_atoms) > 0:
            system = restrain_atoms(system, crds, np.array(lig_heavy_atoms)[:,0], rst_name='lig_k', restraint_strength=86.68*(joule)/(angstrom*angstrom*mole))
        elif self.lig_resname is not None or self.lig_chain is not None:
            raise Exception('Could not find ligand...')

        # Protein Restraint
        system = restrain_atoms(system, crds, np.array(prt_heavy_atoms), rst_name='prot_k', restraint_strength=86.68*(joule)/(angstrom*angstrom*mole))
        
        integrator = LangevinMiddleIntegrator(temp*kelvin, 1/picosecond, dt*femtosecond)
        simulation = Simulation(self.topology, system, integrator)
        simulation.context.setPositions(positions)
        self._describe_state(simulation, "Original state")
        simulation.minimizeEnergy()
        self._describe_state(simulation, "Minimized state")
        end = datetime.now() - start
        print(f'Minimization completed in {end}')
        
        if pdb_out is None:
            pdb_out = os.path.join(self.abs_work_dir, f'minimized.pdb')
        self._write_structure(simulation, pdb_out)

        if state_xml_out is None:
            state_xml_out = os.path.join(self.abs_work_dir, f'minimized.xml')
        self._write_state(simulation, state_xml_out)
            
        return state_xml_out, pdb_out


    def _run_step(self, 
                  state_in:str, 
                  stepnum:int, 
                  state_xml_out:str=None, 
                  pdb_out:str=None,
                  fc_pos:float=300.0, 
                  nsteps=125000, 
                  temp=300.0, 
                  dt=2.0, 
                  ncycles=50, 
                  nstdout=1000,
                  fn_stdout=None, 
                  ndcd=500, 
                  append_dcd: bool=False, 
                  fn_dcd=None, 
                  press=1.0, 
                  positions_from_pdb:str=None,
                  restrain_lig: bool=True):

        """
        Run a single equilibration step with step-specific ensemble and restraints.

        Protocols by step number:

            1 — NVT, protein + membrane Z restraints.
            2 — NPT (MonteCarloMembraneBarostat), protein + membrane Z restraints.
            3 — NVT, protein restraints only.
            4 — NPT (MonteCarloMembraneBarostat), protein restraints only.
            5 — NPT (MonteCarloBarostat), no restraints by default.

        Parameters
        ----------
        state_in : str
            Path to the serialized OpenMM State XML to load (steps 2–5).
        stepnum : int
            Step index (1–5) controlling ensemble and restraints.
        state_xml_out : str, optional
            Output path for the serialized State. Defaults to
            ``<working_directory>/Step_<stepnum>.xml``.
        pdb_out : str, optional
            Output path for the final-frame PDB. Defaults to
            ``<working_directory>/Step_<stepnum>.pdb``.
        fc_pos : float, optional
            Restraint force constant in kJ/mol/nm². Default 300.0.
        nsteps : int, optional
            Total number of integration steps. Default 125000 (250 ps at dt=2 fs).
        temp : float, optional
            Temperature in Kelvin. Default 300.0.
        dt : float, optional
            Timestep in femtoseconds. Default 2.0.
        ncycles : int, optional
            Number of cycles; State XML is checkpointed every cycle. Default 50.
        nstdout : int, optional
            Steps between StateDataReporter entries. Default 1000.
        fn_stdout : str, optional
            Path for the StateDataReporter output file. Defaults to
            ``<working_directory>/step<stepnum>.stdout``.
        ndcd : int, optional
            Steps between DCD frames. Default 500.
        append_dcd : bool, optional
            If True, append to an existing DCD file. Default False.
        fn_dcd : str, optional
            Path for the DCD file. Defaults to
            ``<working_directory>/step<stepnum>.dcd``.
        press : float, optional
            Pressure in bar for NPT steps. Default 1.0.
        positions_from_pdb : str, optional
            Path to a PDB used to identify heavy atoms and set initial
            positions. Required for all steps.
        restrain_lig : bool, optional
            If True, apply positional restraints to ligand heavy atoms.
            Default True.

        Returns
        -------
        state_xml_out : str
            Path to the written State XML after the step.
        pdb_out : str
            Path to the written final-frame PDB after the step.
        """
        #Before ANY STEP
        start = datetime.now()
        #Establish State
        with open(self.system_xml) as f:
            system = XmlSerializer.deserialize(f.read())


        # Get atoms
        assert positions_from_pdb is not None
        crds, prt_heavy, mem_heavy, lig_heavy_atoms = get_positions_from_pdb(positions_from_pdb, lig_resname=self.lig_resname, lig_chain=self.lig_chain)

        # Ligand Restraint
        if restrain_lig:
            if len(lig_heavy_atoms) > 0:
                system = restrain_atoms(system, crds, np.array(lig_heavy_atoms)[:,0], rst_name='lig_k', restraint_strength=86.68*(joule)/(angstrom*angstrom*mole))
            elif self.lig_resname is not None or self.lig_chain is not None:
                raise Exception('Could not find ligand...')   
                
        #STEP SPECIFIC ACTIONS
        if stepnum == 1:
            
            # Protein Restraint
            system = restrain_atoms(system, crds, np.array(prt_heavy), rst_name='prot_k', restraint_strength=86.68*(joule)/(angstrom*angstrom*mole))
            
            #Membrane Restraint
            system = restrain_atoms(system, crds, np.array(mem_heavy), rst_name='mem_k', restraint_strength=86.68*(joule)/(angstrom*angstrom*mole))

        elif stepnum == 2:
            
            # Protein Restraint
            system = restrain_atoms(system, crds, np.array(prt_heavy), rst_name='prot_k', restraint_strength=86.68*(joule)/(angstrom*angstrom*mole))
            
            # Membrane Restraint
            system = restrain_atoms(system, crds, np.array(mem_heavy), rst_name='mem_k', restraint_strength=86.68*(joule)/(angstrom*angstrom*mole))

            # Add MC Membrane Barostat
            system.addForce(MonteCarloMembraneBarostat(press*bar, 300*bar*nanometer, temp*kelvin,
                                                       MonteCarloMembraneBarostat.XYIsotropic,
                                                       MonteCarloMembraneBarostat.ZFree, 100))
            
        elif stepnum == 3:
            # Protein Restraint
            system = restrain_atoms(system, crds, np.array(prt_heavy), rst_name='prot_k', restraint_strength=86.68*(joule)/(angstrom*angstrom*mole))

        elif stepnum == 4:
            # Protein Restraint
            system = restrain_atoms(system, crds, np.array(prt_heavy), rst_name='prot_k', restraint_strength=86.68*(joule)/(angstrom*angstrom*mole))

            # Add MC Membrane Barostat
            system.addForce(MonteCarloMembraneBarostat(press*bar, 300*bar*nanometer, temp*kelvin,
                                                       MonteCarloMembraneBarostat.XYIsotropic,
                                                       MonteCarloMembraneBarostat.ZFree, 100))
        elif stepnum == 5:
            system.addForce(MonteCarloBarostat(press*bar, temp*kelvin, 100))

        else:
            raise NotImplementedError('How did that happen?')
        
        # Any Step Establish Simulation
        integrator = LangevinMiddleIntegrator(temp*kelvin, 1/picosecond, dt*femtosecond)
        simulation = Simulation(self.topology, system, integrator)
        
        # Load Positions
        if stepnum == 1:
            assert positions_from_pdb is not None
            pdb = PDBFile(positions_from_pdb)
            simulation.context.setPositions(pdb.positions)
            simulation.context.setVelocitiesToTemperature(temp)
        else:
            simulation.loadState(state_in)
        
        if fn_stdout is None:
            fn_stdout = os.path.join(self.abs_work_dir, f'step{stepnum}.stdout')
        
        if fn_dcd is None:
            fn_dcd = os.path.join(self.abs_work_dir, f'step{stepnum}.dcd')
        
        SDR = app.StateDataReporter(fn_stdout, nstdout, step=True, time=True,
                                    potentialEnergy=True, temperature=True, progress=False,
                                    remainingTime=True, speed=True, volume=True,
                                    totalSteps=nsteps, separator=' : ')
        
        simulation.reporters.append(SDR)
        DCDR = app.DCDReporter(file=fn_dcd, reportInterval=ndcd, append=append_dcd, enforcePeriodicBox=True)
        simulation.reporters.append(DCDR)
        print(f'Starting Step {stepnum} with forces {simulation.system.getForces()}')
        print(f'Starting Step {stepnum} with box_vectors {simulation.system.getDefaultPeriodicBoxVectors()}')

        # Write out state.xml
        if state_xml_out is None:
            state_xml_out = os.path.join(self.abs_work_dir, f'Step_{stepnum}.xml')

        # Determine no. of steps per cycle
        steps_per_cycle = int(nsteps / ncycles)
                      
        # Reconfigure steps needed to take if appending
        if append_dcd:
            steps_taken = float(simulation.context.getTime().value_in_unit(femtosecond) / dt)
            cycles_completed = math.floor(steps_taken / steps_per_cycle)
            print('steps_taken', steps_taken)
            print('cycles_complete', cycles_completed)
        else:
            cycles_completed = 0
            simulation.context.setTime(0)

        print('ncycles', ncycles)
        print('nsteps', nsteps)
        print('dt', dt)
        print('steps_per_cycle', steps_per_cycle)
        for cycle in range(cycles_completed+1, ncycles+1):
            print('Cycle', cycle, 'to', ((cycle/ncycles) * ((nsteps * dt) / 1e6)), 'ns')
            simulation.step(steps_per_cycle)
            self._describe_state(simulation, f'Step {stepnum}')
            self._write_state(simulation, state_xml_out)

        end = datetime.now() - start
        print(f'Step {stepnum} completed after {end}')
        print(f'Box Vectors after this step {simulation.system.getDefaultPeriodicBoxVectors()}')
        
        if pdb_out is None:
            pdb_out = os.path.join(self.abs_work_dir, f'Step_{stepnum}.pdb')
        self._write_structure(simulation, pdb_out)
        
        for i in range(3):
            print('########################################################################################')
        return state_xml_out, pdb_out
