#!/bin/bash
#SBATCH --job-name="Repex"
#SBATCH --output="/expanse/lustre/projects/uil133/josephdb/%j.%N.ONE_REPEX.out"
#SBATCH --partition=gpu-shared
#SBATCH --gpus=1
#SBATCH --nodes=1
#SBATCH --exclude=exp-1-58
#SBATCH --ntasks-per-node=5
#SBATCH --mem=80G
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=jdepaoloboisvert@hawk.illinoistech.edu
#SBATCH --account=uil133
#SBATCH -t 47:59:59

source ~/.bashrc

conda activate replica2

cd $SLURM_SUBMIT_DIR

python RUN_FULTONMARKET.py "$@"
