#Minimizer
import math
import os
import shutil

import mdtraj as md
import numpy as np
from datetime import datetime
from openmm.app import PDBFile, Simulation
from openmm import XmlSerializer, LangevinIntegrator
from openmm.unit import kelvin, picosecond, femtosecond
from typing import List

from .Minimizer_utils import (unpack_infiles, get_positions_from_pdb,
                              restrain_atoms, parse_atom_inds)

class Minimizer():
    """
    Standalone energy minimizer for OpenMM systems.

    Loads a serialized OpenMM System (XML) and PDB topology, applies optional
    positional restraints to specified ligand atoms, and minimizes the
    structure using a Langevin integrator.

    Parameters
    ----------
    system_xml : str
        Path to the serialized OpenMM System XML generated by Bridgeport.
    pdb_file : str
        Path to the PDB file used to define the topology.
    working_directory : str
        Directory to store minimized output. Created if it does not exist.
    """
    
    def __init__(self, system_xml, pdb_file, working_directory):
        """
        Initialize Minimizer from a serialized OpenMM system and PDB topology.

        See class docstring for parameter descriptions.
        """
        #If the working dir is absolute, leave it alone, otherwise make it abs
        if os.path.isabs(working_directory):
            self.abs_work_dir = working_directory
        else:
            self.abs_work_dir = os.path.join(os.getcwd(), working_directory)
        #Ensure that the working dir exists, and if not create it
        if not os.path.isdir(self.abs_work_dir):
            os.mkdir(self.abs_work_dir)
        #Get the system xml file (we want to create a system fresh from this every time)
        if system_xml is None or os.path.isabs(system_xml):
            pass
        else:
            shutil.copy(system_xml, os.path.join(self.abs_work_dir, system_xml))
            system_xml = os.path.join(self.abs_work_dir, system_xml)

        self.system_xml = system_xml
        
        #Get the pdbfile, store the topology (and initial positions i guess)
        if os.path.isabs(pdb_file):
            pass
        else:
            shutil.copy(pdb_file, os.path.join(self.abs_work_dir, pdb_file))
            pdb_file = os.path.join(self.abs_work_dir, pdb_file)
        
        pdb = PDBFile(pdb_file)
        self.topology = pdb.topology

        
    def main(self, pdb_in):
        """
        Run energy minimization on the input structure.

        Parameters
        ----------
        pdb_in : str
            Path to the input PDB file to minimize.

        Returns
        -------
        state_fn : str
            Path to the serialized OpenMM State XML after minimization.
        pdb_fn : str
            Path to the minimized PDB file.
        """
        #IF the pdb is absolute, store other files in that same directory (where the pdb is)
        if os.path.isabs(pdb_in):
            pass
        else:
            shutil.copy(pdb_in, os.path.join(self.abs_work_dir, pdb_in))
            pdb_in = os.path.join(self.abs_work_dir, pdb_in)
        
        #Minimize
        state_fn, pdb_fn = self._minimize(pdb_in)
        
        return state_fn, pdb_fn
    

    def _describe_state(self, sim: Simulation, name: str = "State"):
        """
        Print the potential energy and maximum force of the simulation.

        Parameters
        ----------
        sim : Simulation
            OpenMM Simulation whose state will be reported.
        name : str, optional
            Label printed alongside the energy. Default ``'State'``.
        """
        state = sim.context.getState(getEnergy=True, getForces=True)
        self.PE = round(state.getPotentialEnergy()._value, 2)
        max_force = round(max(np.sqrt(v.x**2 + v.y**2 + v.z**2) for v in state.getForces()), 2)
        print(f"{name} has energy {self.PE} kJ/mol ", f"with maximum force {max_force} kJ/(mol nm)")
      
        
    def _write_state(self, sim: Simulation, xml_fn: str):
        """
        Serialize the simulation State to an XML file.

        Parameters
        ----------
        sim : Simulation
            OpenMM Simulation whose State will be serialized.
        xml_fn : str
            Output path for the serialized State XML.
        """
        state = sim.context.getState(getPositions=True, getVelocities=True, enforcePeriodicBox=True)
        contents = XmlSerializer.serialize(state)
        with open(xml_fn, 'w') as f:
            f.write(contents)
        print(f'Wrote: {xml_fn}')
 
    
    def _write_system(self, sim: Simulation, xml_fn: str):
        """
        Serialize the simulation System to an XML file.

        Parameters
        ----------
        sim : Simulation
            OpenMM Simulation whose System will be serialized.
        xml_fn : str
            Output path for the serialized System XML.
        """
        with open(xml_fn, 'w') as f:
            f.write(XmlSerializer.serialize(sim.system))
        print(f'Wrote: {xml_fn}')


    def _write_structure(self, sim: Simulation, pdb_fn: str):
        """
        Write the simulation structure to a PDB file.

        Parameters
        ----------
        sim : Simulation
            OpenMM Simulation whose current positions will be written.
        pdb_fn : str
            Output path for the PDB file.
        """
        with open(pdb_fn, 'w') as f:
            PDBFile.writeFile(sim.topology, sim.context.getState(getPositions=True).getPositions(), f, keepIds=True)
        print(f'Wrote: {pdb_fn}')
        

    def _minimize(self, pdb_in:str, pdb_out:str=None, state_xml_out:str=None, temp=300.0, dt=2.0, lig_resname: str=None, mcs: List[str]=None, fc_pos: float=40.0):
        """
        Energy-minimize the structure, writing the result to PDB and XML.

        Parameters
        ----------
        pdb_in : str
            Path to the input PDB file to minimize.
        pdb_out : str, optional
            Output path for the minimized PDB. Defaults to
            ``<working_directory>/minimized.pdb``.
        state_xml_out : str, optional
            Output path for the serialized State XML. Defaults to
            ``<working_directory>/minimized.xml``.
        temp : float, optional
            Temperature in Kelvin for the Langevin integrator. Default 300.0.
        dt : float, optional
            Timestep in femtoseconds. Default 2.0.
        lig_resname : str, optional
            Residue name of the ligand. Required when ``mcs`` is provided.
            Default None.
        mcs : list of str, optional
            Atom names defining the maximum common substructure to restrain.
            When provided with ``lig_resname``, positional restraints are
            applied to matched atoms. Default None.
        fc_pos : float, optional
            Positional restraint force constant in kJ/mol/nm². Default 40.0.

        Returns
        -------
        state_xml_out : str
            Path to the written State XML file.
        pdb_out : str
            Path to the written minimized PDB file.
        """
        start = datetime.now()
        system, _, positions = unpack_infiles(self.system_xml, pdb_in)

        # Add restraint if specified 
        if mcs != None and lig_resname != None:
            crds, prt_heavy_atoms, mem_heavy_atoms, lig_heavy_atoms = get_positions_from_pdb(pdb_in, lig_resname=lig_resname)
            lig_heavy_atom_inds = np.array(lig_heavy_atoms)[:,0].astype(int)
            lig_heavy_atom_names = np.array(lig_heavy_atoms)[:,1]
            mcs_atom_inds = parse_atom_inds(lig_heavy_atom_inds, lig_heavy_atom_names, mcs)

            system = restrain_atoms(system, crds, prt_heavy_atoms, fc_pos)
            system = restrain_atoms(system, crds, mem_heavy_atoms, fc_pos)
            system = restrain_atoms(system, crds, mcs_atom_inds, fc_pos) 

        integrator = LangevinIntegrator(temp*kelvin, 1/picosecond, dt*femtosecond)
        simulation = Simulation(self.topology, system, integrator)
        simulation.context.setPositions(positions)
        self._describe_state(simulation, "Original state")
        simulation.minimizeEnergy()
        self._describe_state(simulation, "Minimized state")
        end = datetime.now() - start
        print(f'Minimization completed in {end}')
        
        if pdb_out is None:
            pdb_out = os.path.join(self.abs_work_dir, f'minimized.pdb')
        self._write_structure(simulation, pdb_out)

        if state_xml_out is None:
            state_xml_out = os.path.join(self.abs_work_dir, f'minimized.xml')
        self._write_state(simulation, state_xml_out)
            
        return state_xml_out, pdb_out

